#  Copyright (C) 2018 Stefan Seefeld
#  Copyright (C) 2019 Cem Bassoy

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.


language: cpp

sudo: required

branches:
  only:
    - master

# env: specifies additional global variables to define per row in build matrix
env:
  global:
    - CLBLAS_PREFIX=${TRAVIS_BUILD_DIR}/CLBLAS/
    - PATH=${CLBLAS_PREFIX}/bin:$PATH
    - LD_LIBRARY_PATH=${CLBLAS_PREFIX}/lib:$LD_LIBRARY_PATH

matrix:
  include:
    - os: linux
      env: TOOLSET=gcc COMPILER=g++-7 CXXSTD=17    
    - os: linux
      env: TOOLSET=clang COMPILER=clang++-6.0 CXXSTD=17
      
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - clang++-6.0
    - libopenblas-base
    - libomp5

install:
  - git clone -b master https://github.com/bassoy/ttv ttv
  - cd ttv
  - export TLIB_ROOT="`pwd`"

# Use before_script: to run configure steps
before_script:

# use script: to execute build steps
script:
  - |-
  - cd ttv/test
  - make -j8
  - ./bin/main

after_success:
  - .ci/report_coverage.sh
  # Uploading to CodeCov
  # '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
  - curl -s https://codecov.io/bash > cov.sh
  - chmod +x cov.sh
  - ./cov.sh -f coverage.info || echo "Codecov did not collect coverage reports"


notifications:
  email:
    on_success: always

